{% set version = "2021.4" %}

package:
  name: gromacs-rid
  version: {{ version }}

build:
  number: 0

source:
  path: ../

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64
    - cmake
    - make
    - fftw * mpi_openmpi_*
    - openmpi 
    - xdrfile
    - plumed-rid
    - cudatoolkit 11.0
    - cudatoolkit-dev 11.0
    - cudnn 8.2
    - libtensorflow_cc 2.6.2 *cuda110*
    - nccl
    - gawk
    - libblas
    - liblapack
    - libopenblas
    

  host:
    - sysroot_linux-64
    - fftw
    - openmpi 
    - xdrfile
    - plumed-rid
    - libhwloc
    - libblas
    - liblapack
    - cudatoolkit 11.0
    - cudnn 8.2
    - libtensorflow_cc 2.6.2 *cuda110*
    - nccl
    - gawk
    - libopenblas

  run:
    - sysroot_linux-64
    - plumed-rid
    - openmpi
    - cudatoolkit 11.0
    - cudnn 8.2
    - nccl
    - libtensorflow_cc 2.6.2 *cuda110*
    - gawk
    - libblas
    - liblapack
    - libopenblas

test:
  commands:
    - gmx -version
    - gmx mdrun -h | grep plumed

about:
  home: http://www.gromacs.org/
  license: GNU Lesser General Public License (LGPL)
  summary: GROMACS is a versatile package to perform molecular dynamics.

