{% set name = "plumed-rid" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
# Most programs should link libplumedWrapper.a so that libplumedKernel.so will be loaded
# with dlopen. There is no need for pinning thus.
# Programs linking libplumed.so should pin to min_pin='x.x', max_pin='x'.
# Programs linking libplumedKernel.so should pin to min_pin='x.x.x'. max_pin='x.x.x'.

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17
    - openmpi
    - make
    - fftw * mpi_openmpi_*
    - libblas
    - liblapack 
    - libopenblas 
    - cudatoolkit 11.0
    - cudatoolkit-dev 11.0
    - cudnn 8.2
    - nccl
    - libtensorflow_cc 2.6.2 *cuda110*
    - xdrfile
    - zlib
    - gsl
  host:
    - sysroot_linux-64 2.17
    - cudatoolkit 11.0
    - cudatoolkit-dev 11.0
    - cudnn 8.2
    - nccl
    - openmpi
    - fftw * mpi_openmpi_*
    - gsl
    - libblas
    - liblapack
    - libopenblas
    - libtensorflow_cc 2.6.2 *cuda110*
    - xdrfile
    - zlib
  run:
    - gawk
    - openmpi
    - libblas
    - liblapack
    - libopenblas
    - cudatoolkit 11.0
    - cudnn 8.2
    - nccl
    - libtensorflow_cc 2.6.2 *cuda110*
    



test:
  commands:
    - plumed info --long-version
    - plumed-patch -h
    - plumed config has external_blas external_lapack fftw gsl xdrfile zlib
    - $PREFIX/lib/plumed/plumed-runtime -h
    - test -f $PREFIX/lib/libplumed$SHLIB_EXT
    - test -f $PREFIX/lib/libplumedWrapper.a
    - test -f $PREFIX/lib/libplumedKernel$SHLIB_EXT

about:
  home: http://www.plumed.org/
  license: LGPL-3.0
  license_family: GPL
  license_file: COPYING.LESSER
  summary: 'Free energy calculations and enhanced sampling in molecular systems'
  description: |
    PLUMED is an open source library for free energy calculations in
    molecular systems which works together with some of the most
    popular molecular dynamics engines.
  doc_url: https://www.plumed.org/doc
  dev_url: https://github.com/plumed/plumed2

extra:
  recipe-maintainers:
    - Dead-fisher
